### ISSUE TITLE
kicked out by strapi status 401

### ISSUE THREAD

**Issue by ninjanoir** [GalloDaSballo/strapi-magic-template#2]
debug GET /magic/settings (380 ms) 401
[2020-12-31T20:39:10.599Z] debug GET /admin/plugins/magic (9 ms) 200
[2020-12-31T20:39:11.471Z] debug GET /admin/init (96 ms) 200
[2020-12-31T20:39:11.634Z] debug GET /favicon.ico (0 ms) 200

**Comment by ninjanoir** [comment]
impossible to get in magic config to paste SK

**Comment by ElyRand** [comment]
same problem here, any updates?

**Comment by GalloDaSballo** [comment]
Are you using a Super Admin to edit the Magic PK?

**Comment by ElyRand** [comment]
Yes a super admin account

**Comment by GalloDaSballo** [comment]
See https://github.com/GalloDaSballo/strapi-magic-template/issues/1
Also download latest (just released) version 0.8.0
