### ISSUE TITLE
Module resolve error when building Strapi admin UI

### ISSUE THREAD

**Issue by FredieU** [GalloDaSballo/strapi-magic-template#3]
After installing this package and re-building the Strapi admin UI, it seems to fail due to:
```
Error: Module not found: Error: Can't resolve '../../components/StrapiStyled' in 'strapi-plugin-magic/admin/src/containers/HomePage'
```

I have checked these 2 files in this repo and it seems to be a mismatched name in the import in [HomePage - line 12](https://github.com/GalloDaSballo/strapi-magic-template/blob/main/plugins/magic/admin/src/containers/HomePage/index.js)
```js
import {Container, Block } from '../../components/StrapiStyled'
```

The [referenced component](https://github.com/GalloDaSballo/strapi-magic-template/blob/main/plugins/magic/admin/src/components/strapiStyled.js) is named `strapiStyled.js`.

I have amended this in my local `node_modules` and it fixed it, did I miss something during the installation/setup of the package or is this a genuine bug?

Many thanks.

**Comment by GalloDaSballo** [comment]
Does this happen if you:
Install a fresh Strapi install
Install the plugin https://www.npmjs.com/package/strapi-plugin-magic
And rebuild?

**Comment by KRIXUS-alpha** [comment]
> Does this happen if you:
> Install a fresh Strapi install
> Install the plugin https://www.npmjs.com/package/strapi-plugin-magic
> And rebuild?

Yes, faced the same issue as described in the OP (tried rebuilding, upgrading Strapi version from 3.4.3 to 3.4.6 -> failed to handle the error and rolled back to previous version@3.4.3),
**Solution**
Compiles fine when the [referenced component](https://github.com/GalloDaSballo/strapi-magic-template/blob/main/plugins/magic/admin/src/components/strapiStyled.js) name is edited from strapiStyled.js to StrapiStyled.js as mention by @FredieU in the OP.

Thanks

**Comment by GalloDaSballo** [comment]
Renamed strapiStyled to StrapiStyled, thank you for the catch

**Comment by FredieU** [comment]
Thanks!
