### ISSUE TITLE
Configure custom role in login

### ISSUE THREAD

**Issue by alexvais** [GalloDaSballo/strapi-magic-template#4]
Hi, how are you?

First of all, congrats for the plugin, it's very helpful!

I've been looking at the code and I see that the default (authenticated) role is automatically set. I'm trying to implement that you can define the role for each new user but I can't find a way to do it. The only idea i have is customize the plugin and pass the role in the variable "ctx" as a header, but i don't know if this is a good solution.

Do you know of other ways to create the user with a specific role in strapi?

thanks!!

**Comment by GalloDaSballo** [comment]
Hey Alex, the plugin uses the default role, you can change the default role from the settings page:
http://localhost:1337/admin/settings/users-permissions/advanced-settings

<img width="1337" alt="Screenshot 2021-04-21 at 20 06 40" src="https://user-images.githubusercontent.com/13383782/115600524-1775cb80-a2dd-11eb-836b-ef8e3703603e.png">

**Comment by alexvais** [comment]
@GalloDaSballo thanks for your response.

but if i want to use more than one role? like "publisher role" and "reader role"?
